// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_List = require("rescript/lib/js/belt_List.js");

function encode(v, indentLevel) {
  return JSON.stringify(v, null, indentLevel);
}

function string(prim) {
  return prim;
}

function $$int(i) {
  return i;
}

function $$float(prim) {
  return prim;
}

function bool(prim) {
  return prim;
}

var $$null = null;

function array(arr, encodeI) {
  return arr.map(Curry.__1(encodeI));
}

function list(l, encodeI) {
  return Belt_List.toArray(l).map(Curry.__1(encodeI));
}

var object = Js_dict.fromArray;

function dict(obj) {
  return obj;
}

function tuple2(param, encodeI, encodeJ) {
  var a$p = Curry._1(encodeI, param[0]);
  var b$p = Curry._1(encodeJ, param[1]);
  return [
          a$p,
          b$p
        ];
}

exports.encode = encode;
exports.string = string;
exports.$$int = $$int;
exports.$$float = $$float;
exports.bool = bool;
exports.$$null = $$null;
exports.array = array;
exports.list = list;
exports.object = object;
exports.dict = dict;
exports.tuple2 = tuple2;
/* null Not a pure module */
